[versions]
stonecutter = "0.8.3"
stonecutter-postprocess = "2.1-beta.8"
mod-publish = "0.8.4"
dotenv-gradle = "4.0.0"
fabric-loom = "1.15-SNAPSHOT"
neoforge-moddev = "2.0.140"
foojay = "1.0.0"
fabric-loader= "0.18.4"

[libraries]
kikugie-postprocess = { module = "dev.kikugie:postprocess", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv-gradle" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
jsonlang-postprocess = { id = "dev.kikugie.postprocess.jsonlang", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }


